CREATE TABLE IF NOT EXISTS players (
    id         TEXT PRIMARY KEY,
    nickname   TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
